HeadHunter/Controllers/EmployerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace HeadHunter.Controllers
{
    public class EmployerController : Controller
    {
        HeadHunter.Models.Entity.HeadHunterEntities db = new Models.Entity.HeadHunterEntities();
        // GET: Employer
        [HttpGet]
        public ActionResult SendMail(int id)
        {
            var user = db.Account.Find(id);

            int _AccountId = id;
            string mail = db.Account.FirstOrDefault(m => m.AccountId == _AccountId).AccountMail;
            string body = "Merhaba," + System.Environment.NewLine +
                "        Sizin için bir iş teklifi var eğer ilgileniyorsanız bu maile cevap vererek teklif yapan firmanın ileşim bilgilerini alabilirsiniz.";
            var fromAddress = new MailAddress("headhuntersystem@gmail.com");
            var toAddress = new MailAddress(mail);
            const string subject = "HeadHunter | İşte size bir iş teklifi";
            using (var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(fromAddress.Address, "headhunter9090")
            })
            {
                using (var message = new MailMessage(fromAddress, toAddress) { Subject = subject, Body = body })
                {
                    smtp.Send(message);
                }
            }

            
            return View();
        }
        [HttpPost]
        public ActionResult SendMail()
        {
            int _profileId=2;
            int _AccountId=_profileId;
            string mail =  db.Account.FirstOrDefault(m => m.AccountId == _AccountId).AccountMail;
            string body = "hi";
            var fromAddress = new MailAddress("headhuntersystem@gmail.com");
            var toAddress = new MailAddress(mail);
            const string subject = "HeadHunter | İşte size bir iş teklifi";
            using (var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(fromAddress.Address, "headhunter9090")
            })
            {
                using (var message = new MailMessage(fromAddress, toAddress) { Subject = subject, Body = body })
                {
                    smtp.Send(message);
                }
            }

            Response.Write("mail başarıyla gönderildi.");
            return View();
        }


        [AuthorizeRoleAttribute(RoleNames.Employer)]
        public ActionResult Profile()
        {


            return View();
        }

        [AuthorizeRoleAttribute(RoleNames.Employer)]
        public ActionResult Home()
        {
            return View();
        }

        [AuthorizeRoleAttribute(RoleNames.Employer)]
        public ActionResult Search()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search(FormCollection collection)
        {
            List<string> FilterPL = new List<string>();
      
            foreach(var key in collection.Keys)
            {
                var getFilterType = key.ToString().Substring(0, 3);
                var filter = ((string[])(collection.GetValue(key.ToString()).RawValue));
                switch (getFilterType)
                {
                    case "PL_":
                        if (filter.Length > 1)
                            FilterPL.Add(filter[0]);
                        break;
                }
                //Console.WriteLine(key.ToString() + " = " + collection.GetValue(key.ToString()).RawValue.ToString());
            }
            var arrFilter = FilterPL.ToArray();
            var countFilter = arrFilter.Length;
            var profilePL = db.ViewProfileProgramLanguage.Where(x => arrFilter.Contains(x.SourceDataTypeName)).GroupBy(x => x.ProfileId).Where(x => x.Count() == countFilter).Select(x => x.Key).ToArray();

            //Sorgusu yazılacak
            //bu kısım filtreleri and ile birleştirmek için bu kısımda ekleme yapılıyor
            var profileRS = profilePL;//yeni filtre

            var lastPL = from p1 in profilePL
                         from p2 in profileRS.Where(x => x == p1)
                             // from p3 in profileGN.Where(x => x== p1)
                             // from p4 in profileLG.Where(x => x== p1)
                         select p1;
            ViewBag.ProfileList = db.Profil.Where(x => lastPL.Contains(x.ProfileId)).ToList();
            return View();
        }
    }
}

HeadHunter/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HeadHunter.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

      
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
       

        //[AuthorizeRoleAttribute(RoleNames.Employer, RoleNames.Employee)]
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Blog()
        {
            ViewBag.Message = "Blog Page";

            return View();
        }
    }
}

HeadHunter/Views/Employer/Home.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_LayoutWithoutLogin.cshtml";
}

<h2>Home</h2>

HeadHunter/Views/Employer/Profile.cshtml
@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Shared/_LayoutWithoutLogin.cshtml";
}



<style>

    body {
        background: -webkit-linear-gradient(left, #3931af, #00c6ff);
    }

    .emp-profile {
        padding: 3%;
        margin-top: 3%;
        margin-bottom: 3%;
        border-radius: 0.5rem;
        background: #fff;
    }

    .profile-img {
        text-align: center;
    }

        .profile-img img {
            width: 70%;
            height: 100%;
        }

        .profile-img .file {
            position: relative;
            overflow: hidden;
            margin-top: -20%;
            width: 70%;
            border: none;
            border-radius: 0;
            font-size: 15px;
            background: #212529b8;
        }

            .profile-img .file input {
                position: absolute;
                opacity: 0;
                right: 0;
                top: 0;
            }

    .profile-head h5 {
        color: #333;
    }

    .profile-head h6 {
        color: #0062cc;
    }

    .profile-edit-btn {
        border: none;
        border-radius: 1.5rem;
        width: 90%;
        padding: 2%;
        font-weight: 600;
        color: #6c757d;
        cursor: pointer;
        margin-bottom: 5%;
    }

    .proile-rating {
        font-size: 12px;
        color: #818182;
        margin-top: 5%;
    }

        .proile-rating span {
            color: #495057;
            font-size: 15px;
            font-weight: 600;
        }

    .profile-head .nav-tabs {
        margin-bottom: 5%;
    }

        .profile-head .nav-tabs .nav-link {
            font-weight: 600;
            border: none;
        }

            .profile-head .nav-tabs .nav-link.active {
                border: none;
                border-bottom: 2px solid #0062cc;
            }

    .profile-work {
        padding: 14%;
        margin-top: -15%;
    }

        .profile-work p {
            font-size: 12px;
            color: #818182;
            font-weight: 600;
            margin-top: 10%;
        }

        .profile-work a {
            text-decoration: none;
            color: #495057;
            font-weight: 600;
            font-size: 14px;
        }

        .profile-work ul {
            list-style: none;
        }

    .profile-tab label {
        font-weight: 600;
    }

    .profile-tab p {
        font-weight: 600;
        color: #0062cc;
    }
</style>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <title></title>
</head>
<body>

    <div class="container emp-profile">
        <form method="post">
            <div class="row">
                <div class="col-md-4">
                    <div class="profile-img">
                        <img src="https://img.utdstc.com/icons/headhunter-android.png:l" alt="" />

                    </div>
                </div>
                <div class="col-md-6">
                    <div class="profile-head">
                        <h5>
                        </h5>
                        <h6>
                            Web Developer and Designer

                        </h6>
                     
                        <ul class="nav nav-tabs">
                            <li class="nav active"><a data-toggle="tab" href="#one">About</a></li>
                            <li class="nav"><a data-toggle="tab" href="#two">Profile</a></li>
                        </ul>

                        <div class="tab-content">

                            <!-- Show this tab by adding `active` class -->
                            <div class="tab-pane fade in active" id="one">
                                <div class="col-md-8">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Employer Name</label>
                                        </div>
                                        <div class="col-md-6">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Name</label>
                                        </div>
                                        <div class="col-md-6">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Email</label>
                                        </div>
                                        <div class="col-md-6">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Phone</label>
                                        </div>
                                        <div class="col-md-6">
                                            <p>123 456 7890</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Profession</label>
                                        </div>
                                        <div class="col-md-6">
                                            <p>Software Employer</p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!-- I removed `in` class here so it will have a fade in effect when showed -->
                            <div class="tab-pane fade" id="two">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Experience</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>Expert</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Hourly Rate</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>10$-15$/hr</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Total Projects</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>230</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>English Level</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>Expert</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Availability</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>6 months</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <label>Your Bio</label><br />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                   
                </div>
            </div>
            <div class="col-md-4">
                <div class="profile-work">
                    <p>WORK LINK</p>
                    <a href="">Website Link</a><br />
                    <a href="">Bootsnipp Profile</a><br />
                    <a href="">Bootply Profile</a>
                    <p>SKILLS</p>
                    <a href="">Web Designer</a><br />
                    <a href="">Web Developer</a><br />
                    <a href="">WordPress</a><br />
                    <a href="">WooCommerce</a><br />

                </div>
            </div>
        </form>
    </div>


</body>
</html>

<style>

    body {
        background-image: linear-gradient(to right, #ff8177 0%, #ff867a 0%, #ff8c7f 21%, #f99185 52%, #cf556c 78%, #b12a5b 100%);
    }
</style>

HeadHunter/Views/Employer/Search.cshtml
@{
    /**/

    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_LayoutWithoutLogin.cshtml";
}

<html>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<head>

</head>

<body>
    <header>
    </header>
   
        <div class="container">
            <div class="row justify-content-center">
                <div class="col=12 mt-3">
                    <div class="jumbotron ">
                        <h2 class="display-4">Select Language or Languages!</h2>
                        @using (Html.BeginForm("Search", "Employer"))
                        {
                            var db = new HeadHunter.Models.Entity.HeadHunterEntities();
                            foreach (var item in db.ViewProgramLanguage)
                            {
                                <div>

                                    @Html.CheckBox("PL_" + item.SourceDataTypeName, new { value = item.SourceDataTypeName })
                                    @Html.Label(item.SourceDataTypeName)

                                </div>

                            }



                            <input type="submit" value="Search" class="btn btn-info btn-primary" />
                            <br />
                            <br />
                            <br />
                            <br />
                            var db_ = new HeadHunter.Models.Entity.HeadHunterEntities();


                            if (ViewBag.ProfileList != null)
                            {
                                @Html.Raw("<table>");
                                @Html.Raw("<tr><td><b>ProfileName</b></td></tr>");

                                var profileList = (List<HeadHunter.Models.Entity.Profil>)ViewBag.ProfileList;
                                foreach (var profile in profileList)
                                {
                                    var accountProfile = db_.Account.FirstOrDefault(m => m.AccountId == profile.AccountId);
                                    <div class="form-group">
                                        @Html.Raw("<tr>")
                                        @Html.Raw(@"<td><a target=""_blank"" href=""/Employee/Profile/" + profile.ProfileId + @""">" + profile.ProfileUsername + "</a>  </td>")
                                        <td><a href="/Employer/SendMail/@profile.AccountId" class="btn btn-success">Send Mail</a></td>
                                        @*<td><a href="/ExportToExcel/ExporttoExcel/" class="btn btn-info">XML Export</a></td>*@

                                        @Html.Raw("</tr>")
                                    </div>
                                }
                                @Html.Raw("</table>");
                            }

                        }
                    </div>
                </div>
            </div>
        </div>
       
</body>

</html>

<style>

    body {
        background-image: linear-gradient(to right, #ff8177 0%, #ff867a 0%, #ff8c7f 21%, #f99185 52%, #cf556c 78%, #b12a5b 100%);
    }
</style>

HeadHunter/Views/Employer/SendMail.cshtml
@model HeadHunter.Models.Entity.Account
@{
    ViewBag.Title = "SendMail";
    Layout = "~/Views/Shared/_LayoutWithoutLogin.cshtml";
}

<h1>Send mail</h1>
<html>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<body>
    <div class="form-group">
        <p class="alert-success">Mail Sent Successfully</p>

        <a href="/Employer/Search/" class="btn btn-success">Ok</a>
    </div>



    @using (Html.BeginForm("SendMail", "Employer", FormMethod.Post))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.AccountFullName)
            @Html.TextBox("Text")
            <br />
            <input type="submit" value="Send Parameter" />
        </div>

    }

</body>
</html>

<style>

    body {
        background-image: linear-gradient(to right, #ff8177 0%, #ff867a 0%, #ff8c7f 21%, #f99185 52%, #cf556c 78%, #b12a5b 100%);
    }
</style>